spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/event_notification_db?currentSchema=public
    username: postgres
    password: ENC(mTZeRkFnIM+ttfKNKWYw9cTXqLcsXG2GsdyiAFxgWR3AY2QmgMPBxXO1e7Uj14rQ)
  jackson:
    default-property-inclusion: non_empty
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
springdoc.api-docs:
  path: /api/docs
  resolve-schema-properties: true

scheduler:
  enabled: true
  event-notifications:
    cron: 50 * * * * ?

http.clients:
  default:
    retry:
      attempts: 3
      min-backoff: 3000
